// packages/reason-editor/svelte/Root.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Editor } from '../src/Editor';
  import { docFromDom } from '../src/rendering/html';

  export let editor;
  let className = '';
  export { className as class };

  let root: HTMLElement | undefined;
  let lastEditor: Editor | undefined;

  $: updateEditor(editor, root);

  function updateEditor(editor: Editor, root?: HTMLElement) {
    if (!root) return;
    if (lastEditor) {
      lastEditor.destroy();
    }
    lastEditor = editor;
    if (editor) {
      editor.setRoot(root);
    }
  }

  onMount(() => {
    if (!root) return;
    const old = Array.from(root.childNodes);
    if (editor && root.children.length) {
      editor.set(docFromDom(editor, root));
    }
    return () => {
      for (let i = 0; i < old.length; i++) root?.appendChild(old[i]);
    };
  });
</script>

<div bind:this={root} class={className}>
  <slot></slot>
</div>

// packages/reason-editor/react/Root.tsx
import React, { useEffect, useRef } from 'react';
import { Editor } from '../src/Editor';
import { docFromDom } from '../src/rendering/html';

export interface RootProps {
    editor: Editor;
    className?: string;
    children?: React.ReactNode;
}

export const Root: React.FC<RootProps> = ({ editor, className = '', children }) => {
    const rootRef = useRef<HTMLDivElement>(null);
    const lastEditorRef = useRef<Editor | undefined>(undefined);

    useEffect(() => {
        const root = rootRef.current;
        if (!root) return;

        if (lastEditorRef.current && lastEditorRef.current !== editor) {
            lastEditorRef.current.destroy();
        }
        lastEditorRef.current = editor;

        if (editor) {
            editor.setRoot(root);
        }
    }, [editor]);

    useEffect(() => {
        const root = rootRef.current;
        if (!root) return;

        const old = Array.from(root.childNodes);
        if (editor && root.children.length) {
            editor.set(docFromDom(editor, root));
        }

        return () => {
            // Restore original children on unmount
            for (let i = 0; i < old.length; i++) {
                root.appendChild(old[i]);
            }
        };
    }, []); // Run once on mount

    return (
        <div ref={rootRef} className={className}>
            {children}
        </div>
    );
};
